### PR TITLE
Initial checkin of homework

### PR DESCRIPTION
**Pull request by jasong-peakbagger**
Let me know what you think..

### CODE REVIEW

**Comment by jamdon** [comment]
Everything works great when using what the module returns as a constructor, but this is not exactly the revealing module pattern. By returning a constructor, this means it can instantiate multiple instances of an enhanced date object. The idea behind the revealing module pattern is to create private internals for the module that the returned methods can continue to have access to. Since each instance you create with a constructor will have that same access, the first instance you create can now change the internally stored date for the second instance you create. For this version of the module pattern, you really only want to work with a singleton object and just return a simple object with your methods on it. Hopefully that explanation makes sense. If not, let me know and I'll provide some code that demonstrates what I'm trying to say.

**Comment by jasong-peakbagger** [comment]
Hi James - thanks for the feedback. I felt like I might have been going down the wrong path here on my initial commit. I think I've got this working as expected now as revealing module pattern. I have yet to use it as a node module, that is coming next.

**Comment by jamdon** [comment]
This is looking better, but remember that any method should check the internally stored date instance before trying to use it. When testing this, the first thing I do is try to call `getDate()` and it errors out because the date instance isn't set yet. The same is true for the other 4 methods that aren't `setDate()`

**Comment by jasong-peakbagger** [comment]
Hopefully I've nailed this down. I've tested it when passing in a date and by running each function by itself. If the date isn't passed in, then each function should work off an internally stored date.

**Comment by jasong-peakbagger** [comment]
Hopefully I've nailed this down. I've tested it when passing in a date and by running each function by itself. If the date isn't passed in, then each function should work off an internally stored date.

**Comment by jasong-peakbagger** [comment]
Hopefully I've nailed this down. I've tested it when passing in a date and by running each function by itself. If the date isn't passed in, then each function should work off an internally stored date.

**Comment by jamdon** [comment]
This is fine, although ideally each method would check if the internally stored date was null, then set it if it was (it gets set to null by default instead of a new date instance.) That said, it's functional now. 👍

**Pull request closed without merging**
